"""add_gin_indexs

Revision ID: 0002
Revises: 0001_create_vacancies
Create Date: 2026-02-27 16:00:40.686940
"""

from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001_create_vacancies'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_city_name_trgm', 'vacancies', ['city_name'], unique=False, postgresql_using='gin', postgresql_ops={'city_name': 'gin_trgm_ops'})
    op.create_index('idx_vacancies_timetable_mode_name_trgm', 'vacancies', ['timetable_mode_name'], unique=False, postgresql_using='gin', postgresql_ops={'timetable_mode_name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vacancies_timetable_mode_name_trgm', table_name='vacancies', postgresql_using='gin', postgresql_ops={'timetable_mode_name': 'gin_trgm_ops'})
    op.drop_index('idx_city_name_trgm', table_name='vacancies', postgresql_using='gin', postgresql_ops={'city_name': 'gin_trgm_ops'})
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
